### ISSUE TITLE
DOC: Instalação dos certificados das AC 

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/docker#24]
Na versão 5.1.x do siga, é necessário definir o diretório onde estão localizados os certificados das autoridades certificadoras para evitar o erro abaixo.

![image](https://cloud.githubusercontent.com/assets/2985140/15785868/f40c90b4-298f-11e6-8d2b-d5720f891fe3.png)

**Comment by raphaelpaiva** [comment]
@Markenson aconteceu novamente? Ou essa issue é pra parametrizar o diretório?

**Comment by raphaelpaiva** [comment]
@Markenson Esquece, agora que vi que é no siga-docker.
