### ISSUE TITLE
Erro no Importador XML

### ISSUE THREAD

**Issue by paulobezerra-trt23** [projeto-siga/docker#7]
Ao tentar mandar importar o arquivo XML de usuários, da um erro que não existe a classe "br.gov.jfrj.siga.dp.DpLotacao" !!!!

O importador foi compilado da ultima versão do sistema.
![erroimportadorxml](https://cloud.githubusercontent.com/assets/9990363/6739950/cddd8892-ce52-11e4-9d79-bef01a7c378f.JPG)

**Comment by kmacedovarela** [comment]
O nome correto da propriedade seria -Dsiga.properties.file, poderia testar novamente com esta propriedade ajustada?

**Comment by paulobezerra-trt23** [comment]
Corrigi a propriedade e gerou o mesmo erro !

**Comment by kmacedovarela** [comment]
Ok vamos verificar, obrigada

**Comment by paulobezerra-trt23** [comment]
Foi nos passado um outro importador que consegue executar mas após ele exibir algumas inconsistências no arquivo XML e corrigido os dados o importador retorna um erro de NullPointerException, fiz um outro teste deixando apenas uma tag <pessoa> e as outras tags do jeito que estavam e continua a dar o erro.
![erroimportadorxml2](https://cloud.githubusercontent.com/assets/9990363/6870041/c66dcda6-d46f-11e4-8e49-6cd23245efd6.JPG)

**Comment by paulobezerra-trt23** [comment]
Coloquei os símbolos de maior e menor no comment anterior e o texto dentro foi suprimido, o correto é:
"fiz um outro teste deixando apenas uma tag "Pessoa" e as outras tags do jeito...."
