### ISSUE TITLE
Schema da base de conhecimento

### ISSUE THREAD

**Issue by paulobezerra-trt23** [projeto-siga/docker#8]
Como estou em testes na base do oracle via docker não sendo possivel fazer a atualização da imagem do oracle, gostaria de pedir um dump do schema da base de conhecimento para a devida atualização localmente.

**Comment by crivano** [comment]
Oi Paulo,

os arquivos SQL para criação da base de conhecimento estão disponíveis no branch "vraptor", em:

https://github.com/projeto-siga/siga/tree/vraptor/sigagc/src/main/resources/db/migration

Abs!
